exports.lang = {
    zh_cn:{
        //登录页
        login_username:"用户名",
        login_hyzh:"请输入会员账号",
        login_dlmm:"密  码",
        login_dlmmpsw:"请输入密码",
        login_wjmm:"忘记密码",
        login_btn:"登录",        
        // 忘记密码
        forget_title:'找回密码',
        forget_zhyzm:'请输入验证码',
        forget_hqyzm:'获取验证码',
        forget_szdlmm:'设置登录密码',
        forget_qrdlmm:'确认登录密码',
        forget_zc:'注册',
        //首页
        // 头部
        index_team0:'团队构架',
        index_team01:'我的团队',
        index_team02:'我的直推',
        index_team03:'直推列表',
        index_jiaoyi0:'交易',
        index_jiaoyi01:'大厅',
        index_jiaoyi02:'出让',
        index_jiaoyi03:'转账',
        index_jiaoyi04:'币种转换',
        index_jylist0:'交易记录',
        index_jylist01:'购买记录',
        index_jylist02:'出让记录',
        index_jylist03:'转账记录',
        index_jylist04:'股票记录',
        index_jylist05:'推荐奖',
        index_jylist06:'对碰奖',
        index_jylist07:'领导奖',
        index_grzx0:'个人中心',
        index_grzx01:'个人中心',
        index_grzx02:'一级密码',
        index_grzx03:'二级密码',
        index_liuyan:'留言',
        index_shop:'商城',
        index_quit:'退出登录',
        //会员资料
        index_hyzl:'会员资料',
        index_xjb:'现金币',
        index_zcb:'注册币',
        index_jhb:'激活币',
        index_xfb:'消费币',
        index_hgb:'回购币',
        index_ipob:'IPO币',
        index_name:'姓名',
        index_yhm:'用户名',
        index_hyjb:'会员级别',
        index_phone:'手机号',
        // 投资升级
        index_tztop:'最高收益率',
        index_tzleft:'起投金额',
        index_tzcenter:'平台保障',
        index_tzright:'短期回报',
        index_tzbtn:'投资升级',
        index_tzwan:'1000万',
        
        // 股票
        index_gpznum:'总股量',
        index_gpyjy:'已交易股量',
        index_gphyid:'会员ID数量',
        index_gppdid:'排队中ID数量',
        // 系统公告
        index_gonggao:'系统公告',
        // 投资升级页
        invest_title:'投资升级',
        invest_left:'理财能手',
        invest_right:'收益颇丰',
        invest_top:'选择理财',
        invest_jhb:'激活币',
        invest_zcb:'注册币',
        invest_zfmm:'支付密码',
        invest_srzfmm:'请输入支付密码',
        invest_sj:'升级',
        // 我的团队
       level_title:'我的团队',
       level_sousuo:'搜索用户',
       level_zhuce:'注册',
       level_zong:'总',
       level_yu:'余',
       level_renshu:'人数',
       level_dengji:'等级',
       level_zcvip:'注册会员',
       //注册
       reg_title:'注册',
       reg_zh:'账号',
       reg_vipphone:'会员手机号',
       reg_sfz:'身份证号',
       reg_tjr:'推荐人账号',
       reg_jdr:'接点人',
       reg_qu:'当前选择的是',
       reg_zuoqu:'左区',
       reg_youqu:'右区',
       reg_dlmm:'登录密码',
       reg_dzdlmm:'设置登录密码',
       reg_qrdlmm:'确认登录密码',
       reg_zfmm:'支付密码',
       reg_xzdj:'选择等级',
       reg_ejmm:'二级密码',
       reg_srejmm:'请输入二级密码',
       reg_zc:'注册',
       //我的直推
       team_title:'我的直推',
        //直推列表
       teamlists_title:'直推列表',
       teamlists_shang:'上一页',
        teamlists_xia:'下一页',
         //  出让
         sell_title:'出让',
         sell_csnum:'出让数量',
         sell_srcsnum:'请输入数量',
         sell_mm:'支付密码',
         // 转账
         give_title:'转账',
         give_zzzh:'转账账户',
         give_zznum:'转账数量',
         give_jymm:'交易密码',
         //币种转换
     change_title:'币种转换',
     change_bz:'币种',
     change_zhhbz:'转换后币种',
     change_cz:'操作',
     change_zh:'转换',
     change_zhnum:'转换数量',
     change_srzhnum:'请输入转换数量',
        // 交易大厅
         dating_title:'交易大厅',
         dating_csr:'出让人',
         dating_cssl:'出让数量',
         dating_sxje:'所需金额',
         dating_ck:'查看',
         dating_xxxx:'详细信息',
         dating_ddh:'订单号',
         dating_csje:'出让金额',
         dating_phone:'手机号',
         dating_zfb:'支付宝',
         dating_wx:'微信',
         dating_khh:'开户行',
         dating_yhkh:'银行卡号',
         dating_khname:'开户姓名',
         dating_cstime:'出让时间',
         dating_close:'取消',
         dating_buy:'购买',
       
        //出让记录
       selllists_title:'出让记录',
       selllists_buyhao:'买家账号', 
       selllists_jyzt:'交易状态', 
       selllists_wfk:'未付款', 
       selllists_yfk:'已付款，待确认', 
       selllists_qrwc:'已完成',
       selllists_qrsk:'确认收款',
         //购买记录
       buylists_yfk:'已付款，待处理', 
       selllists_qrsk:'确认付款',
        //  转账记录
       givelists_zzhy:'转账会员',
       givelists_jshy:'接收会员',
       givelists_zzsl:'转账数量',
       givelists_zztime:'转账时间',
       givelists_chutime:'转出记录',
       givelists_rutime:'转入记录',
       

       // 股票记录 
       gupiao_title:'股票记录',
       gupiao_buylist:'购买记录',  
       gupiao_sellist:'出让记录',  
       gupiao_pgje:'配股金额',  
       gupiao_cjj:'成交价',  
       gupiao_cjl:'成交量',  
       gupiao_buytime:'购买时间',  
       gupiao_dqzt:'当前状态',
       gupiao_cfcs:'拆分次数',
       gupiao_seltime:'出让时间', 
       gupiao_dqss:'当前股数',  
       gupiao_ypg:'已配股',  
       //推荐奖

       tuijian_syly:'收益来源',
       tuijian_sye:'收益额',
       tuijian_sytime:'收益时间',
      //个人中心
        mine_xgtx:'修改头像',
        mine_zsname:'真实姓名',
        mine_username:'用户名',
        mine_hyjb:'会员级别',
        mine_phone:'手机号',
        mine_id:'身份证号',
        mine_zfb:'支付宝',
        mine_weiixn:'微信',
        mine_khh:'开户行',
        mine_yhkh:'银行卡号',
        ine_khdz:'开户行地址',
        ine_khname:'开户姓名',
        ine_email:'邮箱',
        ine_xgzl:'修改资料',
        ine_xiugai:'修   改',
        ine_newphone:'设置新手机号',
        
        mine_zfb0:'请输入支付宝',
        mine_weiixn0:'请输入微信',
        mine_khh0:'请输入开户行',
        mine_yhkh0:'请输入银行卡号',
        ine_khdz0:'请输入开户行地址',
        ine_khname0:'请输入开户姓名',
        ine_email0:'请输入邮箱',
        ine_newphone0:'请输入新手机号',
        mine_yzm:'请输入验证码',
        mine_queren:'确认',
// 修改密码
xiugai_yiji:'修改一级密码',
xiugai_erji:'修改二级密码',
xiugai_phone:'请输入手机号',
xiugai_yijimm:'设置一级密码',
xiugai_qryjmm:'确认一级密码',
xiugai_erjimm:'设置二级密码',
xiugai_qrejmm:'确认二级密码',
// 留言
liuyan0:'请输入留言',
xing:'星',    
cftp:'拆分图谱',  
liuyan_list:'留言记录',
huifu:'回复',
liuyank:"留言框",

vipzsname:"会员真实姓名",
tjrnamea:"推荐人姓名",


    },
    en_us:{
        //登录页
        login_username:"user name",
        login_hyzh:"Please enter your account number",
        login_dlmm:"password",
        login_dlmmpsw:"Please enter your password",
        login_wjmm:"forget the password",
        login_btn:"login",
        //忘记密码
        forget_title:'retrieve password',
        forget_zhyzm:'Please enter the verification code',
        forget_hqyzm:'get code',
        forget_szdlmm:'Set login password',
        forget_qrdlmm:'Confirm login password',
        forget_zc:'register',
        //首页
        //头部
        index_team0:'Team Structure',
        index_team01:'My team',
        index_team02:'Direct drive',
        index_team03:'Straight push list',
        index_jiaoyi0:'Deal',
        index_jiaoyi01:'The hall',
        index_jiaoyi02:'Sell',
        index_jiaoyi03:'Transfer accounts',
        index_jiaoyi04:'Currency conversion',
        index_jylist0:'Trading Record',
        index_jylist01:'Purchase record',
        index_jylist02:'Sell records',
        index_jylist03:'Transfer record',
        index_jylist04:'Stock record',
        index_jylist05:'Referral bonus',
        index_jylist06:'To touch the prize',
        index_jylist07:'Leadership award',
        index_grzx0:'Personal Center',
        index_grzx01:'Personal center',
        index_grzx02:'Level I password',
        index_grzx03:'Level II Password',
        index_liuyan:'Leave Word',
        index_shop:'Mall',
        index_quit:'Log out',
        // 会员资料
        index_hyzl:'Member Information',
        index_xjb:'Cash money',
        index_zcb:'Registered currency',
        index_jhb:'Activate the currency',
        index_xfb:'Spending money',
        index_hgb:'Repurchase currency',
        index_ipob:'IPO currency',
        index_name:'name',
        index_yhm:'username',
        index_hyjb:'Membership grade',
        index_phone:'cell-phone number',
         // 投资升级
        index_tztop:'Maximum rate of return',
        index_tzleft:'The investment amount',
        index_tzcenter:'terrace guarantee',
        index_tzright:'Short-term returns',
        index_tzbtn:'Investment to upgrade',
        index_tzwan:'10 million',
        // 股票
        index_gpznum:'total stock',
        index_gpyjy:'Traded shares',
        index_gphyid:'vip ID member',
        index_gppdid:'ID number in queue',
        // 系统公告
        index_gonggao:'System of announcement',
       // 投资升级页
       invest_title:'Investment to upgrade',
       invest_left:'Financial experts',
       invest_right:'Highly profitable',
       invest_top:'select manage money matters ',
       invest_jhb:'Activate the currency',
       invest_zcb:'Registered currency',
       invest_zfmm:'payment code',
       invest_srzfmm:'Please enter the payment password',
       invest_sj:'Upgrade',
        // 我的团队
        level_title:'My team',
        level_sousuo:'Search the user',
        level_zhuce:'register ',
        level_zong:'total',
        level_yu:'surplus',
        level_renshu:'number people',
        level_dengji:'grade',
        level_zcvip:'register member',
         //注册
       reg_title:'register',
       reg_zh:'account number',
       reg_vipphone:'cell-phone number',
       reg_sfz:'ID number',
       reg_tjr:'Recommender account',
       reg_jdr:'Contact person',
       reg_qu:'The current choice is',
       reg_zuoqu:' left area',
       reg_youqu:' right area',
       reg_dlmm:'login password',
       reg_dzdlmm:'Set login password',
       reg_qrdlmm:'Confirm login password',
       reg_zfmm:'payment code',
       reg_xzdj:'Select level',
       reg_ejmm:'secondary password',
       reg_srejmm:'Please enter your second password',
       reg_zc:'register',
         //我的直推
       team_title:'I direct push',
       //直推列表
       teamlists_title:'Straight push list',
       teamlists_shang:'previous page',
       teamlists_xia:'next page',
      
       //  出让
       sell_title:'sell',
       sell_csnum:'Sell quantity',
       sell_srcsnum:'Please enter the quantity',
       sell_mm:'password',   
        // 转账
        give_title:'Transfer',
        give_zzzh:'accounts',
        give_zznum:'number',
        give_jymm:' password',
    //币种转换
    change_title:'Currency conversion',
    change_bz:'currency',
    change_zhhbz:'Converted currency',
    change_cz:'operation',
    change_zh:'conversion',
    change_zhnum:'number',
    change_srzhnum:'Please enter the conversion number',
      // 交易大厅
      dating_title:'trading floor',
      dating_csr:'Sell the person',
      dating_cssl:'Sell quantity',
      dating_sxje:'The amount needed',
      dating_ck:'look over',
      dating_xxxx:'detailed information',
      dating_ddh:'order number ',
      dating_csje:'The sale amount',
      dating_phone:'cell-phone number',
      dating_zfb:'alipay',
      dating_wx:'WeChat ',
      dating_khh:'opening bank',
      dating_yhkh:'credit card numbers',
      dating_khname:'To open an account name',
      dating_cstime:'Selling time',
      dating_close:'cancel',
      dating_buy:'buy',
        //出让记录
        selllists_title:'All Selling',
        selllists_buyhao:'Buyers account', 
        selllists_jyzt:'Transaction status', 
        selllists_wfk:'non-payment ', 
        selllists_yfk:'Payment has been made', 
        selllists_qrwc:'Completed',
        selllists_qrsk:'collection confirmation',
          //购买记录
       buylists_yfk:'account paid', 
       selllists_qrsk:'confirm payment',
         //  转账记录
         givelists_zzhy:'Transfer member',
         givelists_jshy:'Members receive',
         givelists_zzsl:'Transfer number',
         givelists_zztime:'Transfer time',
         givelists_chutime:'Transfer record',
       givelists_rutime:'To record',
       
         
        // 股票记录 
       gupiao_title:'update everyday',
       gupiao_buylist:'purchase history',  
       gupiao_sellist:'All Selling',  
       gupiao_pgje:'A rights issue amount',  
       gupiao_cjj:'transaction price ',  
       gupiao_cjl:' turnover',  
       gupiao_buytime:'purchasing date',  
       gupiao_dqzt:'current status ',
       gupiao_cfcs:'Break up the number',
       gupiao_seltime:'Selling time', 
       gupiao_dqss:'The current number of shares',  
       gupiao_ypg:'Have a rights issue',  
        //推荐奖
 
        tuijian_syly:'Source of income',
        tuijian_sye:'Returns the forehead',
        tuijian_sytime:'Returns the time',
      //个人中心
      mine_xgtx:'Modify the picture',
      mine_zsname:'real name',
      mine_username:'user name ',
      mine_hyjb:'Membership grade',
      mine_phone:'cell-phone',
      mine_id:'ID number',
      mine_zfb:'alipay',
      mine_weiixn:'WeChat ',
      mine_khh:'bank of deposit',
      mine_yhkh:'credit card numbers',
      ine_khdz:'bank address',
      ine_khname:'open account name',
      ine_email:' mailbox',
      ine_xgzl:'modified data',
      ine_xiugai:'modified',
      ine_newphone:'set new phone',
      mine_zfb0:'Please enter alipay',
      mine_weiixn0:'Please enter WeChat ',
      mine_khh0:'Please enter bank of deposit',
      mine_yhkh0:'Please enter credit card numbers',
      ine_khdz0:'Please enter bank address',
      ine_khname0:'Please enter open account name',
      ine_email0:'Please enter mailbox',
      ine_newphone0:'Please enter set new phone',
      mine_yzm:'Please enter verification code',
      mine_queren:'notarize',
      // 修改密码
xiugai_yiji:'modification Level I password',
xiugai_erji:'modification Level II password',
xiugai_phone:'Please enter phone',
xiugai_yijimm:'set Level I password',
xiugai_qryjmm:'affirm Level I password',
xiugai_erjimm:'set Level II password',
xiugai_qrejmm:'affirm Level II password',
// 留言
liuyan0:'Please enter the your message',
xing:'start', 
cftp:'split atlas',   
liuyan_list:'Message record',
huifu:'reply',
liuyank:"message box",

vipzsname:"Member name",
tjrnamea:"Name of referee",

    }
}